<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bridge.Provider.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bridge.Core\Bridge.Core.csproj" />
    <ProjectReference Include="..\Bridge.Security\Bridge.Security.csproj" />
  </ItemGroup>

</Project>
